In [ ]:
'''
해당 jupyter 버전
openpyxl-3.1.2
'''

In [6]:
import pandas as pd
import openpyxl

In [23]:
# 모든 데이터 출력

#pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [24]:
df = pd.read_excel('../data/Hwaseong_data.xlsx')
df.head()

,월별,행정기관,총인구,총인구_남,총인구_여,내국인,내국인_남,내국인_여,외국인,외국인_남,외국인_여,등록외국인,등록외국인_남,등록외국인_여,외국국적동포,외국국적동포_남,외국국적동포_여,지가지수,지가변동률_전국,지가변동률_수도권,지가변동률_지방,지가변동률_대도시,지가변동률_시지역,지가변동률_군지역,지가변동률_화성시,매매가격지수_아파트_전국,매매가격지수_아파트_수도권,매매가격지수_아파트_지방권,매매가격지수_아파트_6대광역시,매매가격지수_아파트_5대광역시,매매가격지수_아파트_9개도,매매가격지수_아파트_8개도,매매가격지수_아파트_서울,매매가격지수_아파트_화성시,매매가격변동률_아파트_전국,매매가격변동률_아파트_수도권,매매가격변동률_아파트_지방권,매매가격변동률_아파트_6대광역시,매매가격변동률_아파트_5대광역시,매매가격변동률_아파트_9개도,매매가격변동률_아파트_8개도,매매가격변동률_아파트_서울,매매가격변동률_아파트_화성시,전세가격지수_아파트_전국,전세가격지수_아파트_수도권,전세가격지수_아파트_지방권,전세가격지수_아파트_6대광역시,전세가격지수_아파트_5대광역시,전세가격지수_아파트_9개도,전세가격지수_아파트_8개도,전세가격지수_아파트_서울,전세가격지수_아파트_화성시,전세가격변동률_아파트_전국,전세가격변동률_아파트_수도권,전세가격변동률_아파트_지방권,전세가격변동률_아파트_6대광역시,전세가격변동률_아파트_5대광역시,전세가격변동률_아파트_9개도,전세가격변동률_아파트_8개도,전세가격변동률_아파트_서울,전세가격변동률_아파트_화성시,월세가격지수_아파트_전국,월세가격지수_아파트_수도권,월세가격지수_아파트_지방권,월세가격지수_아파트_6대광역시,월세가격지수_아파트_5대광역시,월세가격지수_아파트_9개도,월세가격지수_아파트_8개도,월세가격지수_아파트_서울,월세가격지수_아파트_화성시,월세가격변동률_아파트_전국,월세가격변동률_아파트_수도권,월세가격변동률_아파트_지방권,월세가격변동률_아파트_6대광역시,월세가격변동률_아파트_5대광역시,월세가격변동률_아파트_9개도,월세가격변동률_아파트_8개도,월세가격변동률_아파트_서울,월세가격변동률_아파트_화성시,총전입,총전출,순이동,출생자수,출생자수_남자,출생자수_여자,사망자수,사망자수_남자,사망자수_여자,PI_P,PI_C,PI_SI,PI_PA,CD,CP,YT_1,YT_3,YT_5,YT_10,CB_3_AA,CB_3_BBB,BaseRate,실업률,CPI_F,CPI_C,CPI_H,CPI_HE,CPI_T,CPI_E,CPI_M
0,2014-01-01,화성시,561418,296851,264567,530567,273924,256643,30851,22927,7924,26486,20101,6385,4365,2826,1539,76.251,0.107,0.112,0.097,0.153,0.065,0.047,0.008,80.221,71.359,89.642,77.591,79.045,84.495,100.885,73.212,74.156,0.37,0.30,0.44,0.43,0.46,0.36,0.42,0.29,0.28,81.407,74.708,88.446,78.904,81.359,85.010,96.284,76.398,79.457,0.87,1.19,0.55,0.71,0.58,0.86,0.53,1.20,1.69,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6516,6576,-60,514,256,258,149,84,65,96.0,84.2138,91.3,87.0,2.65,2.83,2.657,2.892,3.258,3.647,3.319,9.019,2.5,3.2,85.705,93.172,89.865,95.224,110.321,94.986,86.312
1,2014-02-01,화성시,561970,297221,264749,530912,274128,256784,31058,23093,7965,26634,20230,6404,4424,2863,1561,76.233,0.142,0.142,0.143,0.180,0.112,0.077,-0.024,80.473,71.614,89.883,77.836,79.287,84.751,101.122,73.462,74.270,0.31,0.36,0.27,0.32,0.31,0.30,0.24,0.34,0.15,81.992,75.487,88.795,79.353,81.734,85.647,96.606,77.076,80.474,0.72,1.04,0.39,0.57,0.46,0.75,0.33,0.89,1.28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8345,8332,13,497,243,254,179,97,82,94.9,79.9905,90.9,88.0,2.65,2.78,2.640,2.854,3.161,3.522,3.280,8.974,2.5,3.6,86.581,93.180,90.473,95.205,110.130,95.185,86.941
2,2014-03-01,화성시,563241,297929,265312,532001,274736,257265,31240,23193,8047,26716,20258,6458,4524,2935,1589,76.308,0.199,0.215,0.168,0.254,0.148,0.151,0.098,80.762,71.952,90.104,78.095,79.489,85.059,101.365,73.750,74.543,0.36,0.47,0.25,0.33,0.26,0.36,0.24,0.39,0.37,82.570,76.285,89.109,79.860,82.051,86.271,96.924,77.663,81.638,0.71,1.06,0.35,0.64,0.39,0.73,0.33,0.76,1.45,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7713,6977,736,536,258,278,184,100,84,95.7,79.0099,91.0,87.9,2.65,2.77,2.659,2.874,3.169,3.543,3.303,8.994,2.5,3.4,86.810,93.310,90.681,95.260,110.050,95.900,87.724
3,2014-04-01,화성시,564807,298885,265922,533061,275361,257700,31746,23524,8222,27178,20565,6613,4568,2959,1609,76.352,0.180,0.178,0.183,0.203,0.157,0.151,0.058,80.859,71.968,90.301,78.278,79.675,85.132,101.576,73.776,74.655,0.12,0.02,0.22,0.23,0.23,0.09,0.21,0.04,0.15,82.766,76.454,89.333,80.100,82.271,86.471,97.163,77.783,82.109,0.24,0.22,0.25,0.30,0.27,0.23,0.25,0.15,0.58,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6640,6024,616,590,296,294,159,81,78,95.7,84.8951,90.3,88.8,2.65,2.76,2.653,2.875,3.168,3.540,3.303,8.998,2.5,3.6,86.733,93.277,90.297,95.150,109.879,95.936,87.783
4,2014-05-01,화성시,566485,299882,266603,534076,275882,258194,32409,24000,8409,27806,21043,6763,4603,2957,1646,76.583,0.152,0.151,0.153,0.169,0.138,0.117,0.302,80.892,71.925,90.431,78.396,79.799,85.152,101.716,73.713,74.740,0.04,-0.06,0.14,0.15,0.16,0.02,0.14,-0.09,0.11,82.850,76.493,89.469,80.248,82.409,86.557,97.309,77.771,82.283,0.10,0.05,0.15,0.18,0.17,0.10,0.15,-0.02,0.21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6336,5740,596,546,282,264,139,74,65,92.8,81.0606,90.9,86.0,2.65,2.76,2.641,2.838,3.082,3.402,3.264,8.957,2.5,3.5,86.741,93.740,91.030,95.196,109.749,95.973,88.174

In [25]:
df.describe()

,총인구,총인구_남,총인구_여,내국인,내국인_남,내국인_여,외국인,외국인_남,외국인_여,등록외국인,등록외국인_남,등록외국인_여,외국국적동포,외국국적동포_남,외국국적동포_여,지가지수,지가변동률_전국,지가변동률_수도권,지가변동률_지방,지가변동률_대도시,지가변동률_시지역,지가변동률_군지역,지가변동률_화성시,매매가격지수_아파트_전국,매매가격지수_아파트_수도권,매매가격지수_아파트_지방권,매매가격지수_아파트_6대광역시,매매가격지수_아파트_5대광역시,매매가격지수_아파트_9개도,매매가격지수_아파트_8개도,매매가격지수_아파트_서울,매매가격지수_아파트_화성시,매매가격변동률_아파트_전국,매매가격변동률_아파트_수도권,매매가격변동률_아파트_지방권,매매가격변동률_아파트_6대광역시,매매가격변동률_아파트_5대광역시,매매가격변동률_아파트_9개도,매매가격변동률_아파트_8개도,매매가격변동률_아파트_서울,매매가격변동률_아파트_화성시,전세가격지수_아파트_전국,전세가격지수_아파트_수도권,전세가격지수_아파트_지방권,전세가격지수_아파트_6대광역시,전세가격지수_아파트_5대광역시,전세가격지수_아파트_9개도,전세가격지수_아파트_8개도,전세가격지수_아파트_서울,전세가격지수_아파트_화성시,전세가격변동률_아파트_전국,전세가격변동률_아파트_수도권,전세가격변동률_아파트_지방권,전세가격변동률_아파트_6대광역시,전세가격변동률_아파트_5대광역시,전세가격변동률_아파트_9개도,전세가격변동률_아파트_8개도,전세가격변동률_아파트_서울,전세가격변동률_아파트_화성시,월세가격지수_아파트_전국,월세가격지수_아파트_수도권,월세가격지수_아파트_지방권,월세가격지수_아파트_6대광역시,월세가격지수_아파트_5대광역시,월세가격지수_아파트_9개도,월세가격지수_아파트_8개도,월세가격지수_아파트_서울,월세가격지수_아파트_화성시,월세가격변동률_아파트_전국,월세가격변동률_아파트_수도권,월세가격변동률_아파트_지방권,월세가격변동률_아파트_6대광역시,월세가격변동률_아파트_5대광역시,월세가격변동률_아파트_9개도,월세가격변동률_아파트_8개도,월세가격변동률_아파트_서울,월세가격변동률_아파트_화성시,총전입,총전출,순이동,출생자수,출생자수_남자,출생자수_여자,사망자수,사망자수_남자,사망자수_여자,PI_P,PI_C,PI_SI,PI_PA,CD,CP,YT_1,YT_3,YT_5,YT_10,CB_3_AA,CB_3_BBB,BaseRate,실업률,CPI_F,CPI_C,CPI_H,CPI_HE,CPI_T,CPI_E,CPI_M
count,112.000000,112.000000,112.000000,112.000000,112.000000,112.000000,112.000000,112.000000,112.000000,112.000000,112.000000,112.000000,112.000000,112.000000,112.000000,112.000000,112.000000,112.000000,112.000000,112.000000,112.000000,112.000000,112.000000,112.000000,112.000000,112.000000,112.000000,112.000000,112.000000,112.00000,112.000000,112.000000,112.000000,112.000000,112.000000,112.000000,112.000000,112.000000,112.000000,112.000000,112.000000,112.000000,112.000000,112.000000,112.000000,112.000000,112.000000,112.000000,112.000000,112.000000,112.000000,112.000000,112.000000,112.000000,112.000000,112.000000,112.000000,112.000000,112.000000,95.000000,95.000000,95.000000,95.000000,95.000000,95.000000,95.000000,95.000000,95.000000,94.000000,94.000000,94.000000,94.000000,94.000000,94.000000,94.000000,94.000000,94.000000,112.000000,112.000000,112.000000,112.000000,112.000000,112.000000,112.000000,112.000000,112.000000,111.000000,111.000000,111.000000,111.000000,112.000000,112.000000,112.000000,112.000000,112.000000,112.000000,112.000000,112.000000,112.000000,112.000000,112.000000,112.000000,112.000000,112.000000,112.000000,112.000000,112.000000
mean,775813.794643,409555.008929,366258.785714,732112.544643,379235.687500,352876.857143,43701.250000,30319.321429,13381.928571,35535.383929,25824.982143,9710.401786,8165.866071,4494.339286,3671.526786,86.961482,0.263571,0.284741,0.227875,0.305304,0.229080,0.188339,0.243589,89.920982,85.306518,94.708455,87.979884,88.870893,91.866152,100.89817,88.577866,85.071884,0.137321,0.228125,0.050893,0.139821,0.121161,0.109375,-0.013393,0.214464,0.144018,92.206518,89.831241,94.578000,89.557018,90.532446,94.570554,99.352429,91.241571,90.518777,0.076250,0.106964,0.044107,0.079554,0.061696,0.063214,0.022232,0.094286,-0.016696,101.397442,101.353011,101.448716,100.578484,100.611716,101.969558,102.461389,101.487947,102.669926,0.003085,0.017766,-0.010851,0.016383,0.006702,0.000851,-0.025532,-0.016702,-0.012553,11596.473214,8432.669643,3163.803571,573.419643,292.919643,280.500000,213.642857,115.803571,97.839286,100.184685,96.558758,100.382883,96.380180,1.717054,1.960357,1.715464,1.925277,2.104875,2.334688,2.543759,8.613804,1.535714,3.590179,97.069143,98.917509,98.359286,98.365348,104.291196,100.106491,97.542768
std,135280.578703,70888.677492,64394.171762,129875.605561,68128.613881,61750.039411,5832.219305,3236.713332,2695.235582,3650.545136,2375.884685,1388.179029,2683.599074,1310.892197,1380.947983,7.954908,0.101103,0.126232,0.079333,0.126713,0.083106,0.065544,0.112227,7.421599,10.869384,4.504029,7.889265,7.073191,6.815394,4.30454,9.731100,11.140210,0.652910,0.803819,0.543844,0.714649,0.669543,0.670766,0.467997,0.629574,1.140475,5.850978,7.702129,4.264595,6.540535,5.830128,5.175366,3.498558,7.153092,6.898549,0.764705,1.002613,0.562060,0.789482,0.721691,0.722101,0.433610,0.918482,1.329323,1.674434,1.658134,1.959744,1.696763,1.638996,1.822372,2.496534,1.416477,1.572214,0.143684,0.169764,0.140618,0.143548,0.139449,0.158064,0.151179,0.147126,0.294888,2996.507961,1886.866072,1713.442822,49.238460,28.358115,27.052168,52.399171,27.243262,27.273904,5.770776,9.455396,6.320168,7.600979,0.740461,0.827790,0.730600,0.748957,0.723358,0.683702,0.830911,0.788716,0.715700,0.424043,8.800197,3.307697,5.218835,1.883156,5.998668,2.150632,6.590080
min,561418.000000,296851.000000,264567.000000,530567.000000,273924.000000,256643.000000,30851.000000,22927.000000,7924.000000,26486.000000,20101.000000,6385.000000,4365.000000,2826.000000,1539.000000,76.233000,-0.036000,-0.048000,-0.021000,-0.073000,-0.020000,-0.005000,-0.024000,80.221000,71.359000,88.929000,77.591000,79.045000,84.495000,92.57200,73.212000,74.156000,-2.910000,-3.660000,-2.220000,-3.110000,-2.700000,-2.750000,-1.700000,-2.960000,-4.690000,81.407000,74.708000,88.446000,78.904000,81.359000,85.010000,92.906000,76.398000,75.943000,-3.650000,-4.970000,-2.400000,-3.670000,-3.190000,-3.280000,-1.640000,-4.800000,-7.190000,99.041000,99.472000,98.587000,98.335000,98.306000,99.336000,99.148000,99.753000,100.000000,-0.180000,-0.340000,-0.240000,-0.170000,-0.170000,-0.240000,-0.330000,-0.340000,-0.970000,5724.000000,5359.000000,-60.000000,428.000000,222.000000,206.000000,131.000000,68.000000,51.000000,91.000000,77.822800,90.300000,83.600000,0.630000,0.970000,0.611000,0.826000,1.092000,1.254000,1.645000,7.721000,0.500000,2.600000,85.705000,93.172000,89.865000,94.802000,95.700000,94.986000,86.312000
25%,653900.000000,344932.500000,308967.500000,615737.750000,317788.250000,297949.500000,38496.000000,27674.500000,11018.000000,33297.750000,24519.500000,8698.000000,5429.000000,3109.000000,2320.000000,79.201000,0.198500,0.191250,0.197500,0.235250,0.165750,0.159250,0.174750,86.083500,77.570500,91.317000,83.976000,85.482750,87.643000,97.72725,79.682000,78.148000,-0.030000,0.007500,-0.170000,-0.042500,-0.052500,-0.067500,-0.295000,-0.010000,-0.062500,88.762250,86.563750,91.156750,86.368750,87.381250,90.582750,97.084500,88.507750,86.520750,-0.107500,-0.102500,-0.162500,-0.135000,-0.120000,-0.222500,-0.202500,0.002500,-0.367500,99.864500,100.323500,99.579000,99.144000,99.117500,100.163500,99.978500,100.391000,101.557000,-0.090000,-0.077500,-0.110000,-0.080000,-0.090000,-0.100000,-0.120000,-0.107500,-0.147500,9304.750000,6941.000000,2115.750000,551.500000,279.500000,265.000000,179.750000,96.000000,79.000000,95.700000,91.079700,96.250000,90.400000,1.380000,1.590000,1.321500,1.405750,1.575000,1.827500,2.001750,8.094000,1.250000,3.475000,89.084750,96.785500,94.423500,97.224000,99.612250,99.136500,93.353500
50%,786470.500000,415280.500000,371190.000000,740272.000000,383059.500000,357212.500000,46129.500000,30871.500000,13977.500000,35483.000000,25377.000000,10219.000000,8252.000000,4493.500000,3758.500000,86.185000,0.300000,0.324000,0.239000,0.329000,0.252500,0.193000,0.281000,87.383500,82.436500,94.430500,85.000500,86.411000,89.867000,102.14550,90.891000,79.606500,0.115000,0.240000,0.010000,0.115000,0.100000,0.035000,-0.045000,0.270000,0.130000,91.452000,89.056000,94.261500,87.980000,89.025000,94.503000,100.021000,91.692500,89.409500,0.150000,0.230000,0.075000,0.140000,0.105000,0.140000,0.065000,0.230000,0.145000,101.316000,100.687000,101.689000,100.384000,100.609000,102.033000,102.345000,100.881000,102.705000,-0.060000,-0.030000,-0.060000,-0.040000,-0.050000,-0.060000,-0.050000,-0.035000,-0.040000,11711.500000,8372.500000,3102.500000,575.000000,292.000000,279.000000,203.500000,111.500000,94.000000,99.100000,98.463200,100.100000,94.700000,1.635000,1.735000,1.584000,1.775000,1.925500,2.218500,2.239000,8.412000,1.500000,3.600000,94.975000,99.111000,98.227000,98.411000,102.749000,100.358500,96.702500
75%,903533.250000,476275.750000,427257.500000,855823.500000,444164.500000,411659.000000,48403.250000,33108.750000,15762.750000,38579.750000,27753.250000,10788.000000,10198.000000,5393.250000,4804.750000,93.940750,0.335000,0.385250,0.269000,0.398000,0.292250,0.225250,0.319250,92.963750,91.464500,95.177250,90.422750,90.817250,92.791750,104.36575,95.919500,89.818500,0.385000,0.542500,0.295000,0.422500,0.402500,0.370000,0.217500,0.560000,0.415000,93.049000,91.528250,95.451250,89.951000,90.661750,96.412500,101.930500,94.034500,92.109500,0.480000,0.632500,0.325000,0.420000,0.372500,0.490000,0.265000,0.495000,0.642500,102.807500,101.967000,103.261500,101.573000,101.934000,103.562500,104.680500,102.654500,103.719500,0.075000,0.037500,0.090000,0.105000,0.085000,0.057500,0.077500,0.020000,0.057500,13509.500000,9616.500000,4193.750000,602.250000,306.250000,299.250000,236.250000,130.250000,112.000000,103.400000,103.328750,103.050000,101.300000,1.877500,1.980000,1.878000,2.203750,2.442500,2.690500,2.788000,8.859250,1.750000,3.900000,104.607500,100.252500,100.439250,99.887500,107.871500,101.699750,100.980000
max,978653.000000,516886.000000,461767.000000,925186.000000,480653.000000,444533.000000,53467.000000,36233.000000,17234.000000,41351.000000,29848.000000,11503.000000,12955.000000,6972.000000,5983.000000,100.116000,0.455000,0.543000,0.383000,0.587000,0.345000,0.307000,0.463000,106.284000,107.927000,104.853000,105.407000,104.240000,107.630000,106.36100,104.382000,111.649000,1.700000,2.220000,1.720000,2.060000,2.420000,1.860000,1.170000,1.840000,3.490000,104.488000,105.320000,103.854000,103.920000,103.286000,105.506000,105.567000,103.488000,105.508000,1.520000,1.330000,1.700000,2.160000,2.230000,1.240000,1.070000,1.250000,1.750000,104.494000,105.672000,104.413000,104.188000,103.706000,105.004000,106.446000,105.080000,105.972000,0.380000,0.470000,0.350000,0.450000,0.430000,0.410000,0.320000,0.440000,0.960000,21532.000000,13888.000000,10153.000000,698.000000,383.000000,336.000000,405.000000,200.000000,206.000000,115.500000,116.371300,115.800000,113.800000,4.020000,5.520000,3.838000,4.235000,4.286000,4.267000,5.487000,11.331000,3.500000,4.800000,116.340000,108.300000,112.030000,102.300000,123.430000,104.240000,115.060000

In [26]:
df.isna().sum()

월별                    0
행정기관                  0
총인구                   0
총인구_남                 0
총인구_여                 0
내국인                   0
내국인_남                 0
내국인_여                 0
외국인                   0
외국인_남                 0
외국인_여                 0
등록외국인                 0
등록외국인_남               0
등록외국인_여               0
외국국적동포                0
외국국적동포_남              0
외국국적동포_여              0
지가지수                  0
지가변동률_전국              0
지가변동률_수도권             0
지가변동률_지방              0
지가변동률_대도시             0
지가변동률_시지역             0
지가변동률_군지역             0
지가변동률_화성시             0
매매가격지수_아파트_전국         0
매매가격지수_아파트_수도권        0
매매가격지수_아파트_지방권        0
매매가격지수_아파트_6대광역시      0
매매가격지수_아파트_5대광역시      0
매매가격지수_아파트_9개도        0
매매가격지수_아파트_8개도        0
매매가격지수_아파트_서울         0
매매가격지수_아파트_화성시        0
매매가격변동률_아파트_전국        0
매매가격변동률_아파트_수도권       0
매매가격변동률_아파트_지방권       0
매매가격변동률_아파트_6대광역시     0
매매가격변동률_아파트_5대광역시     0
매매가격변동률_아파트_9개도       0
매매가격변동률_아파트_8개도       0
매매가격변동률_아파트_서울        0
매매가격변동률_아파트_화성시       0
전세가격지수_아파트_전국         0
전세가격지수_아파트_수도권        0
전세가격지수_아파트_지방권        0
전세가격지수_아파트_6대광역시      0
전세가격지수_아파트_5대광역시      0
전세가격지수_아파트_9개도        0
전세가격지수_아파트_8개도        0
전세가격지수_아파트_서울         0
전세가격지수_아파트_화성시        0
전세가격변동률_아파트_전국        0
전세가격변동률_아파트_수도권       0
전세가격변동률_아파트_지방권       0
전세가격변동률_아파트_6대광역시     0
전세가격변동률_아파트_5대광역시     0
전세가격변동률_아파트_9개도       0
전세가격변동률_아파트_8개도       0
전세가격변동률_아파트_서울        0
전세가격변동률_아파트_화성시       0
월세가격지수_아파트_전국        17
월세가격지수_아파트_수도권       17
월세가격지수_아파트_지방권       17
월세가격지수_아파트_6대광역시     17
월세가격지수_아파트_5대광역시     17
월세가격지수_아파트_9개도       17
월세가격지수_아파트_8개도       17
월세가격지수_아파트_서울        17
월세가격지수_아파트_화성시       17
월세가격변동률_아파트_전국       18
월세가격변동률_아파트_수도권      18
월세가격변동률_아파트_지방권      18
월세가격변동률_아파트_6대광역시    18
월세가격변동률_아파트_5대광역시    18
월세가격변동률_아파트_9개도      18
월세가격변동률_아파트_8개도      18
월세가격변동률_아파트_서울       18
월세가격변동률_아파트_화성시      18
총전입                   0
총전출                   0
순이동                   0
출생자수                  0
출생자수_남자               0
출생자수_여자               0
사망자수                  0
사망자수_남자               0
사망자수_여자               0
PI_P                  1
PI_C                  1
PI_SI                 1
PI_PA                 1
CD                    0
CP                    0
YT_1                  0
YT_3                  0
YT_5                  0
YT_10                 0
CB_3_AA               0
CB_3_BBB              0
BaseRate              0
실업률                   0
CPI_F                 0
CPI_C                 0
CPI_H                 0
CPI_HE                0
CPI_T                 0
CPI_E                 0
CPI_M                 0
dtype: int64